### PR TITLE
Fix: scroll to top button

### PR DESCRIPTION
**Pull request by MrKrishnaAgarwal**
Signed-off-by: Krishna Agarwal <dmkrishna.agarwal@gmail.com>

### CODE REVIEW

**Comment by MrKrishnaAgarwal** [comment]
@devarshishimpi can we discuss this change quickly

**Comment by MrKrishnaAgarwal** [comment]
@devarshishimpi if you visit the stonecss website and move your cursor, you'll see that there is some change of position there, so this pr fixes that issue

**Comment by MrKrishnaAgarwal** [comment]
I don't want hacktoberfest label but this PR fixes a minor issue

**Review by devarshishimpi — APPROVED** [review]
Great!

**Comment by MrKrishnaAgarwal** [comment]
Thanks!!

**Pull request merged**
